
    const team = [
        { name: 'Hamburg SV' },
        { name: 'Borussia Dortmund' },
        { name: 'FC Augsburg' },
        { name: 'SC Freiburg' },
        { name: 'Werder Bremen' },
        { name: 'Kaiserslautern' },
        { name: 'Lorient' },
        { name: 'Paris Saint-Germain' },
        { name: 'Valenciennes' },
        { name: 'Caen' },
        { name: 'Nurnberg' },
        { name: 'Hertha Berlin' },
        { name: 'Brest' },
        { name: 'Evian Thonon Gaillard' },
        { name: 'AC Ajaccio' },
        { name: 'Toulouse' },
        { name: 'Nice' },
        { name: 'Lyon' },
        { name: 'VfL Wolfsburg' },
        { name: 'FC Cologne' },
        { name: 'Lille' },
        { name: 'AS Nancy Lorraine' },
        { name: 'Montpellier' },
        { name: 'AJ Auxerre' },
        { name: 'Schalke 04' },
        { name: 'VfB Stuttgart' },
        { name: 'TSG Hoffenheim' },
        { name: 'Hannover 96' },
        { name: 'Marseille' },
        { name: 'Sochaux' },
        { name: 'Bordeaux' },
        { name: 'St Etienne' },
        { name: 'Dijon FCO' },
        { name: 'Stade Rennes' },
        { name: 'Mainz' },
        { name: 'Bayer Leverkusen' },
        { name: 'Bayern Munich' },
        { name: 'Borussia Monchengladbach' },
        { name: 'Sporting Gijon' },
        { name: 'Real Sociedad' },
        { name: 'Valencia' },
        { name: 'Racing Santander' },
        { name: 'Real Zaragoza' },
        { name: 'Real Madrid' },
        { name: 'Sevilla' },
        { name: 'Malaga' },
        { name: 'Rayo Vallecano' },
        { name: 'Athletic Bilbao' },
        { name: 'Getafe' },
        { name: 'Levante' },
        { name: 'Atletico Madrid' },
        { name: 'Osasuna' },
        { name: 'Mallorca' },
        { name: 'Espanyol' },
        { name: 'Barcelona' },
        { name: 'Villarreal' },
        { name: 'Lazio' },
        { name: 'AC Milan' },
        { name: 'Cesena' },
        { name: 'Napoli' },
        { name: 'Palermo' },
        { name: 'Internazionale' },
        { name: 'Chievo Verona' },
        { name: 'Novara' },
        { name: 'Juventus' },
        { name: 'Parma' },
        { name: 'Real Betis' },
        { name: 'Udinese' },
        { name: 'Lecce' },
        { name: 'Siena' },
        { name: 'Catania' },
        { name: 'AS Roma' },
        { name: 'Cagliari' },
        { name: 'Fiorentina' },
        { name: 'Bologna' },
        { name: 'Atalanta' },
        { name: 'Genoa' },
        { name: 'Granada' },
        { name: 'Stade de Reims' },
        { name: 'Celta Vigo' },
        { name: 'Troyes' },
        { name: 'Bastia' },
        { name: 'Deportivo La Coruna' },
        { name: 'Real Valladolid' },
        { name: 'SpVgg Greuther Furth' },
        { name: 'Fortuna Dusseldorf' },
        { name: 'Eintracht Frankfurt' },
        { name: 'Torino' },
        { name: 'Sampdoria' },
        { name: 'US Pescara' },
        { name: 'AS Monaco' },
        { name: 'Guingamp' },
        { name: 'Nantes' },
        { name: 'Almeria' },
        { name: 'Elche' },
        { name: 'Hellas Verona' },
        { name: 'Sassuolo' },
        { name: 'Livorno' },
        { name: 'TSV Eintracht Braunschweig' },
        { name: 'Aston Villa' },
        { name: 'Hull' },
        { name: 'Fulham' },
        { name: 'Stoke City' },
        { name: 'Sunderland' },
        { name: 'Manchester Utd' },
        { name: 'Liverpool' },
        { name: 'Crystal Palace' },
        { name: 'Manchester City' },
        { name: 'Everton' },
        { name: 'Newcastle' },
        { name: 'Cardiff' },
        { name: 'West Brom' },
        { name: 'Arsenal' },
        { name: 'West Ham' },
        { name: 'Tottenham' },
        { name: 'Chelsea' },
        { name: 'Norwich City' },
        { name: 'Swansea' },
        { name: 'Southampton' },
        { name: 'Metz' },
        { name: 'Lens' },
        { name: 'QPR' },
        { name: 'Leicester City' },
        { name: 'Burnley' },
        { name: 'SC Paderborn' },
        { name: 'Eibar' },
        { name: 'Cordoba' },
        { name: 'Empoli' },
        { name: 'Bournemouth' },
        { name: 'Watford' },
        { name: 'Angers' },
        { name: 'GFC Ajaccio' },
        { name: 'SV Darmstadt 98' },
        { name: 'FC Ingolstadt 04' },
        { name: 'Las Palmas' },
        { name: 'Frosinone' },
        { name: 'Carpi' },
        { name: 'Middlesbrough' },
        { name: 'Alaves' },
        { name: 'Crotone' },
        { name: 'Leganes' },
        { name: 'RB Leipzig' }
        ];